//---------------------------------- 常规设定 ----------------------------------
{$DEFINE Debug}
//调试模式

//----------------------------------- 管理器 -----------------------------------
{$DEFINE TaskMonitor}
//启用任务管理器

{$DEFINE LogManager}
//启用日志管理器

{$DEFINE ThreadPool}
//启用线程管理器

{.$DEFINE RemObjects}
{$DEFINE RO_v90}
//启用RO支持

{$DEFINE DBManager}
//启用数据库管理器

{$DEFINE MenuManager}
//启用菜单管理器
