//---------------------------------- 常规设定 ----------------------------------
{$DEFINE Debug}
//调试模式

//----------------------------------- 管理器 -----------------------------------
{.$DEFINE RemObjects}
{$DEFINE RO_v90}
//启用通道管理器

{$DEFINE TaskMonitor}
//启用任务管理器

{.$DEFINE PlugManager}
//启用插件管理器

{$DEFINE LogManager}
//启用日志管理器

{$DEFINE DBManager}
//启用数据库管理器
{$DEFINE WinADO}
//启用ADO驱动
{$DEFINE EncryptLib}
//启用加解密算法库

{.$DEFINE MenuManager}
//启用数据库管理器

{.$DEFINE DataDictManager}
//启用数据库管理器

{.$DEFINE MQTTMessager}
//启用MQTT消息中心
